# Generated by Django 6.0.7 on 2026-08-10 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('dob', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('resume_file_name', models.CharField(blank=True, max_length=255)),
                ('resume_parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('employment_type', models.CharField(blank=True, max_length=60)),
                ('start_date', models.CharField(blank=True, max_length=40)),
                ('end_date', models.CharField(blank=True, max_length=40)),
                ('current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='accounts.profile')),
            ],
            options={
                'ordering': ['-current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('start_date', models.CharField(blank=True, max_length=40)),
                ('end_date', models.CharField(blank=True, max_length=40)),
                ('current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.profile')),
            ],
            options={
                'verbose_name_plural': 'education',
                'ordering': ['-current', '-start_date'],
            },
        ),
    ]
