# Generated by Django 6.0.7 on 2026-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('naukri', 'Naukri'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('source_job_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('min_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('description', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['source', '-posted_at'], name='jobs_job_source_ae86a8_idx'), models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_job_id'), name='unique_job_per_source')],
            },
        ),
    ]
