# Generated by Django 6.0.7 on 2026-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('naukri', 'Naukri'), ('foundit', 'Foundit'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
    ]
