# Generated by Django 6.0.7 on 2026-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_apply_url_job_is_active_alter_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicant_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='function',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
