# Generated by Django 6.0.7 on 2026-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_applicant_count_job_company_id_job_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_text',
            field=models.TextField(blank=True),
        ),
    ]
