# Generated by Django 6.0.7 on 2026-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('naukri', 'Naukri'), ('foundit', 'Foundit'), ('hirist', 'Hirist'), ('unstop', 'Unstop'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
    ]
