# Generated by Django 6.0.7 on 2026-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_widen_char_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.OrderBy(models.F('posted_at'), descending=True, nulls_last=True), '-created_at']},
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('naukri', 'Naukri'), ('foundit', 'Foundit'), ('hirist', 'Hirist'), ('unstop', 'Unstop'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('instahyre', 'Instahyre')], max_length=20),
        ),
    ]
