# Generated by Django 6.0.7 on 2026-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_job_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_linkedin',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
