# Generated by Django 6.0.7 on 2026-09-04 18:43

from django.db import migrations


def backfill_snapshot(apps, schema_editor):
    """Copy each Application's still-live job onto the new snapshot fields.

    Every existing row still has a job at this point — SET_NULL has never
    fired yet — so this is the only chance to backfill from the live
    relation before a future prune could null it out.
    """
    Application = apps.get_model("applications", "Application")
    for app in Application.objects.select_related("job").filter(job__isnull=False):
        job = app.job
        app.job_title = job.title
        app.job_company = job.company
        app.job_company_logo = job.company_logo
        app.job_source = job.source
        app.job_location = job.location
        app.job_url = job.url
        app.job_apply_url = job.apply_url
        app.save(update_fields=[
            "job_title", "job_company", "job_company_logo",
            "job_source", "job_location", "job_url", "job_apply_url",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_job_apply_url_application_job_company_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_snapshot, migrations.RunPython.noop),
    ]
